; Script generated by the HM NIS Edit Script Wizard.

; HM NIS Edit Wizard helper defines
!define PRODUCT_NAME "WebCourse"
!define PRODUCT_VERSION "GUI 1.0"
!define PRODUCT_PUBLISHER "xeroxYor(菜菜子)"
!define PRODUCT_WEB_SITE "https://mrbeike.github.io/WebCourse-QTGUI/"
!define PRODUCT_UNINST_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}"
!define PRODUCT_UNINST_ROOT_KEY "HKLM"

; MUI 1.67 compatible ------
!include "MUI.nsh"

; MUI Settings
!define MUI_ABORTWARNING
!define MUI_ICON "resource\list.ico"
!define MUI_UNICON "resource\uninstaller.ico"
<<<<<<< HEAD

; Language Selection Dialog Settings
!define MUI_LANGDLL_REGISTRY_ROOT "${PRODUCT_UNINST_ROOT_KEY}"
!define MUI_LANGDLL_REGISTRY_KEY "${PRODUCT_UNINST_KEY}"
!define MUI_LANGDLL_REGISTRY_VALUENAME "NSIS:Language"
=======
>>>>>>> 4681d04a26ea89604aba5ed538c766a6eb86e4d9

; Welcome page
!insertmacro MUI_PAGE_WELCOME
; License page
!define MUI_LICENSEPAGE_CHECKBOX
<<<<<<< HEAD
!insertmacro MUI_PAGE_LICENSE "resource\gpl-3.0.rtf"
=======
!insertmacro MUI_PAGE_LICENSE "gpl-3.0.rtf"
>>>>>>> 4681d04a26ea89604aba5ed538c766a6eb86e4d9
; Directory page
!insertmacro MUI_PAGE_DIRECTORY
; Instfiles page
!insertmacro MUI_PAGE_INSTFILES
; Finish page
<<<<<<< HEAD
!define MUI_FINISHPAGE_RUN "$INSTDIR\${PRODUCT_NAME}"
=======
>>>>>>> 4681d04a26ea89604aba5ed538c766a6eb86e4d9
!insertmacro MUI_PAGE_FINISH

; Uninstaller pages
!insertmacro MUI_UNPAGE_INSTFILES

; Language files
!insertmacro MUI_LANGUAGE "SimpChinese"

; MUI end ------

Name "${PRODUCT_NAME} ${PRODUCT_VERSION}"
<<<<<<< HEAD
OutFile "WebCourseInstaller.exe"
InstallDir "$PROGRAMFILES\${PRODUCT_NAME}"
InstallDirRegKey HKLM "${PRODUCT_DIR_REGKEY}" ""
ShowInstDetails show
ShowUnInstDetails show


Section "WebCourse" SEC01
  SetOutPath "$INSTDIR"
  SetOverwrite on
  File /r "dist\WebCourse"
  CreateDirectory "$SMPROGRAMS\${PRODUCT_NAME}"
  CreateShortCut "$SMPROGRAMS\${PRODUCT_NAME}.lnk" "$INSTDIR\${PRODUCT_NAME}.exe"
  CreateShortCut "$DESKTOP\${PRODUCT_NAME}.lnk" "$INSTDIR\${PRODUCT_NAME}.exe"
=======
OutFile "Setup.exe"
InstallDir "$PROGRAMFILES\WebCourse"
ShowInstDetails show
ShowUnInstDetails show

Section "WebCourse" SEC01
  SetOutPath "$INSTDIR"
  SetOverwrite on
  File "dist\WebCourse\*.*"
  File "dist\WebCourse\user.db"
>>>>>>> 4681d04a26ea89604aba5ed538c766a6eb86e4d9
SectionEnd

Section -AdditionalIcons
  WriteIniStr "$INSTDIR\${PRODUCT_NAME}.url" "InternetShortcut" "URL" "${PRODUCT_WEB_SITE}"
<<<<<<< HEAD
  CreateShortCut "$SMPROGRAMS\${PRODUCT_NAME}\Website.lnk" "$INSTDIR\${PRODUCT_NAME}.url"
  CreateShortCut "$SMPROGRAMS\${PRODUCT_NAME}\Uninstall.lnk" "$INSTDIR\uninst.exe"
=======
  CreateDirectory "$SMPROGRAMS\WebCourse"
  CreateShortCut "$SMPROGRAMS\WebCourse\Website.lnk" "$INSTDIR\${PRODUCT_NAME}.url"
  CreateShortCut "$SMPROGRAMS\WebCourse\Uninstall.lnk" "$INSTDIR\uninst.exe"
>>>>>>> 4681d04a26ea89604aba5ed538c766a6eb86e4d9
SectionEnd

Section -Post
  WriteUninstaller "$INSTDIR\uninst.exe"
<<<<<<< HEAD
  WriteRegStr HKLM "${PRODUCT_DIR_REGKEY}" "" "$INSTDIR\${PRODUCT_NAME}.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayName" "$(^Name)"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "UninstallString" "$INSTDIR\uninst.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayIcon" "$INSTDIR\${PRODUCT_NAME}.exe"
=======
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayName" "$(^Name)"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "UninstallString" "$INSTDIR\uninst.exe"
>>>>>>> 4681d04a26ea89604aba5ed538c766a6eb86e4d9
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayVersion" "${PRODUCT_VERSION}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "URLInfoAbout" "${PRODUCT_WEB_SITE}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "Publisher" "${PRODUCT_PUBLISHER}"
SectionEnd

;onInit该回调将会在当安装程序接近完成初始化时调用，若函数调用了 Abort，则安装程序立即退出。检查程序是否正在运行
Function .onInit
  !insertmacro MUI_LANGDLL_DISPLAY
  ;关闭进程
  Push $R0
  CheckProc:
    Push "${PRODUCT_NAME}.exe"
    ProcessWork::existsprocess
    Pop $R0
    IntCmp $R0 0 Done
    MessageBox MB_OKCANCEL|MB_ICONSTOP "安装程序检测到 ${PRODUCT_NAME} 正在运行。$\r$\n$\r$\n点击 “确定” 强制关闭${PRODUCT_NAME}，继续安装。$\r$\n点击 “取消” 退出安装程序。" IDCANCEL Exit
    Push "${PRODUCT_NAME}.exe"
    Processwork::KillProcess
    Sleep 1000
    Goto CheckProc
    Exit:
    Abort
    Done:
    Pop $R0
FunctionEnd


Function un.onUninstSuccess
  HideWindow
  MessageBox MB_ICONINFORMATION|MB_OK "$(^Name) 已成功地从你的计算机移除。"
FunctionEnd

Function un.onInit
<<<<<<< HEAD
!insertmacro MUI_UNGETLANGUAGE
=======
>>>>>>> 4681d04a26ea89604aba5ed538c766a6eb86e4d9
  MessageBox MB_ICONQUESTION|MB_YESNO|MB_DEFBUTTON2 "你确实要完全移除 $(^Name) ，其及所有的组件？" IDYES +2
  Abort
  ;检测程序是否运行
  FindProcDLL::FindProc "${PRODUCT_NAME}.exe"
  Pop $R0
  IntCmp $R0 1 0 no_run
  MessageBox MB_ICONSTOP "卸载程序检测到 ${PRODUCT_NAME} 正在运行，请关闭之后再卸载！"
  Quit
  no_run:
FunctionEnd

Section Uninstall
  Delete "$INSTDIR\${PRODUCT_NAME}.url"
  Delete "$INSTDIR\uninst.exe"
<<<<<<< HEAD
  Delete "$INSTDIR\${PRODUCT_NAME}.exe"

  Delete "$SMPROGRAMS\${PRODUCT_NAME}\Uninstall.lnk"
  Delete "$SMPROGRAMS\${PRODUCT_NAME}\${PRODUCT_NAME}.lnk"
  Delete "$DESKTOP\${PRODUCT_NAME}.lnk"
  Delete "$SMPROGRAMS\${PRODUCT_NAME}\$$PRODUCT_NAME.lnk"

  RMDir "$SMPROGRAMS\${PRODUCT_NAME}"
  RMDir /r "$INSTDIR" ;删除所有
=======
  Delete "$INSTDIR\user.db"
  Delete "$INSTDIR\*.*"

  Delete "$SMPROGRAMS\WebCourse\Uninstall.lnk"
  Delete "$SMPROGRAMS\WebCourse\Website.lnk"

  RMDir "$SMPROGRAMS\WebCourse"
  RMDir "$INSTDIR"
>>>>>>> 4681d04a26ea89604aba5ed538c766a6eb86e4d9

  DeleteRegKey ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}"
  SetAutoClose true
SectionEnd
<<<<<<< HEAD




function .onInit
    setShellVarContext all
    !insertmacro VerifyUserIsAdmin  
 
    #check program running.
    ${nsProcess::FindProcess} ${APPEXENAME} $R0
    ${If} $R0 == "
        # it's running
        MessageBox MB_OK "软件正在运行，按确定退出!"
        Quit
    ${EndIf}  
 
;    MessageBox MB_OK "当前软件的版本为：${VERSIONLONG}"
    #check version from custom install place
    ReadRegStr $ HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${COMPANYNAME} ${APPNAME}" "MainProgramLocation"
    ${If} $ != ""
;      MessageBox MB_OK "文件位置：$0"
      ${If} ${FileExists} $
;        #if installed version is greater, return 2
;        #else if equality, return 0.
;        #else if less, return 1 and resume install process.
;        #MessageBox MB_OK "Version=$R0"
;       MessageBox MB_OK "before push the parameter for VerCheck function.$0"
       push $
       Call VerCheck
       ${VersionCompare} $VersionNumber ${VERSIONLONG} $R0
       ${"
           MessageBox MB_OK "你已经安装同版本或较新版本${APPNAME}软件，按确定退出安装！"
           Quit
        ${Endif}
      ${EndIf}
;    ${Else}
;      MessageBox MB_ICONSTOP "Not found"
    ${EndIf}
functionEnd  
=======
>>>>>>> 4681d04a26ea89604aba5ed538c766a6eb86e4d9
