# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\lbbas\Desktop\test\pyqt-test\WebCourse\ui\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ICO/list.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setIconSize(QtCore.QSize(64, 64))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(120, 0, 680, 580))
        self.stackedWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.stackedWidget.setObjectName("stackedWidget")
        self.login_page = QtWidgets.QWidget()
        self.login_page.setObjectName("login_page")
        self.password_label = QtWidgets.QLabel(self.login_page)
        self.password_label.setGeometry(QtCore.QRect(170, 270, 51, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.password_label.setFont(font)
        self.password_label.setObjectName("password_label")
        self.logo_label = QtWidgets.QLabel(self.login_page)
        self.logo_label.setGeometry(QtCore.QRect(0, 0, 671, 201))
        font = QtGui.QFont()
        font.setFamily("Albertus Extra Bold")
        font.setPointSize(36)
        self.logo_label.setFont(font)
        self.logo_label.setStyleSheet("image: url(:/IMG/logo.png);")
        self.logo_label.setText("")
        self.logo_label.setAlignment(QtCore.Qt.AlignCenter)
        self.logo_label.setObjectName("logo_label")
        self.password_input = QtWidgets.QLineEdit(self.login_page)
        self.password_input.setGeometry(QtCore.QRect(239, 270, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Albertus Extra Bold")
        font.setPointSize(12)
        self.password_input.setFont(font)
        self.password_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_input.setObjectName("password_input")
        self.username_label = QtWidgets.QLabel(self.login_page)
        self.username_label.setGeometry(QtCore.QRect(170, 210, 51, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.username_label.setFont(font)
        self.username_label.setObjectName("username_label")
        self.login_button = QtWidgets.QPushButton(self.login_page)
        self.login_button.setGeometry(QtCore.QRect(240, 390, 191, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.login_button.setFont(font)
        self.login_button.setFlat(False)
        self.login_button.setObjectName("login_button")
        self.username_input = QtWidgets.QComboBox(self.login_page)
        self.username_input.setGeometry(QtCore.QRect(239, 210, 231, 31))
        self.username_input.setEditable(True)
        self.username_input.setObjectName("username_input")
        self.username_input.addItem("")
        self.remember_check = QtWidgets.QCheckBox(self.login_page)
        self.remember_check.setGeometry(QtCore.QRect(280, 330, 91, 21))
        self.remember_check.setObjectName("remember_check")
        self.stackedWidget.addWidget(self.login_page)
        self.regist_page = QtWidgets.QWidget()
        self.regist_page.setObjectName("regist_page")
        self.regist_list = QtWidgets.QTableView(self.regist_page)
        self.regist_list.setGeometry(QtCore.QRect(10, 70, 661, 451))
        self.regist_list.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.regist_list.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.regist_list.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.regist_list.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.regist_list.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.regist_list.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.regist_list.setWordWrap(True)
        self.regist_list.setObjectName("regist_list")
        self.regist_list.horizontalHeader().setDefaultSectionSize(50)
        self.regist_list.horizontalHeader().setStretchLastSection(False)
        self.keyword_input = QtWidgets.QLineEdit(self.regist_page)
        self.keyword_input.setGeometry(QtCore.QRect(80, 20, 241, 31))
        self.keyword_input.setObjectName("keyword_input")
        self.year_input = QtWidgets.QLineEdit(self.regist_page)
        self.year_input.setGeometry(QtCore.QRect(420, 19, 81, 31))
        self.year_input.setObjectName("year_input")
        self.regist_button = QtWidgets.QPushButton(self.regist_page)
        self.regist_button.setGeometry(QtCore.QRect(200, 530, 281, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.regist_button.setFont(font)
        self.regist_button.setObjectName("regist_button")
        self.search_button = QtWidgets.QPushButton(self.regist_page)
        self.search_button.setGeometry(QtCore.QRect(530, 20, 111, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.search_button.setFont(font)
        self.search_button.setDefault(False)
        self.search_button.setObjectName("search_button")
        self.year_label = QtWidgets.QLabel(self.regist_page)
        self.year_label.setGeometry(QtCore.QRect(350, 20, 71, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.year_label.setFont(font)
        self.year_label.setObjectName("year_label")
        self.keyword_label = QtWidgets.QLabel(self.regist_page)
        self.keyword_label.setGeometry(QtCore.QRect(20, 20, 61, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.keyword_label.setFont(font)
        self.keyword_label.setObjectName("keyword_label")
        self.stackedWidget.addWidget(self.regist_page)
        self.project_page = QtWidgets.QWidget()
        self.project_page.setObjectName("project_page")
        self.detail_button = QtWidgets.QPushButton(self.project_page)
        self.detail_button.setGeometry(QtCore.QRect(340, 530, 120, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.detail_button.setFont(font)
        self.detail_button.setObjectName("detail_button")
        self.project_list = QtWidgets.QTableView(self.project_page)
        self.project_list.setGeometry(QtCore.QRect(10, 10, 660, 511))
        self.project_list.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.project_list.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.project_list.setObjectName("project_list")
        self.learn_button = QtWidgets.QPushButton(self.project_page)
        self.learn_button.setGeometry(QtCore.QRect(200, 530, 120, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.learn_button.setFont(font)
        self.learn_button.setObjectName("learn_button")
        self.stackedWidget.addWidget(self.project_page)
        self.course_page = QtWidgets.QWidget()
        self.course_page.setObjectName("course_page")
        self.course_list = QtWidgets.QTableView(self.course_page)
        self.course_list.setGeometry(QtCore.QRect(10, 10, 660, 511))
        self.course_list.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.course_list.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.course_list.setObjectName("course_list")
        self.learn_button_2 = QtWidgets.QPushButton(self.course_page)
        self.learn_button_2.setGeometry(QtCore.QRect(280, 530, 120, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.learn_button_2.setFont(font)
        self.learn_button_2.setObjectName("learn_button_2")
        self.stackedWidget.addWidget(self.course_page)
        self.lab_page = QtWidgets.QWidget()
        self.lab_page.setObjectName("lab_page")
        self.stackedWidget.addWidget(self.lab_page)
        self.about_page = QtWidgets.QWidget()
        self.about_page.setObjectName("about_page")
        self.thumb_button = QtWidgets.QPushButton(self.about_page)
        self.thumb_button.setGeometry(QtCore.QRect(270, 440, 100, 100))
        self.thumb_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/ICO/thumb.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.thumb_button.setIcon(icon1)
        self.thumb_button.setIconSize(QtCore.QSize(100, 100))
        self.thumb_button.setCheckable(True)
        self.thumb_button.setAutoDefault(False)
        self.thumb_button.setDefault(False)
        self.thumb_button.setFlat(True)
        self.thumb_button.setObjectName("thumb_button")
        self.about_label = QtWidgets.QLabel(self.about_page)
        self.about_label.setEnabled(True)
        self.about_label.setGeometry(QtCore.QRect(110, 40, 431, 381))
        self.about_label.setTextFormat(QtCore.Qt.RichText)
        self.about_label.setWordWrap(True)
        self.about_label.setObjectName("about_label")
        self.donate_label = QtWidgets.QLabel(self.about_page)
        self.donate_label.setEnabled(True)
        self.donate_label.setGeometry(QtCore.QRect(110, 20, 431, 401))
        self.donate_label.setStyleSheet("border-image: url(:/IMG/donate.png);")
        self.donate_label.setText("")
        self.donate_label.setObjectName("donate_label")
        self.stackedWidget.addWidget(self.about_page)
        self.menu_list = QtWidgets.QListWidget(self.centralwidget)
        self.menu_list.setGeometry(QtCore.QRect(0, 0, 120, 580))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.menu_list.setFont(font)
        self.menu_list.setStyleSheet("")
        self.menu_list.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.menu_list.setResizeMode(QtWidgets.QListView.Adjust)
        self.menu_list.setObjectName("menu_list")
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/ICO/lgoin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon2)
        self.menu_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/ICO/regist.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon3)
        self.menu_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/ICO/project.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon4)
        self.menu_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/ICO/course.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon5)
        self.menu_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/ICO/lab.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon6)
        self.menu_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/ICO/about.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon7)
        self.menu_list.addItem(item)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.menu_list.setCurrentRow(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "WebCourse"))
        self.password_label.setText(_translate("MainWindow", "密码"))
        self.username_label.setText(_translate("MainWindow", "账号"))
        self.login_button.setText(_translate("MainWindow", "登  陆"))
        self.username_input.setItemText(0, _translate("MainWindow", "3412245111"))
        self.remember_check.setText(_translate("MainWindow", "记住密码"))
        self.keyword_input.setPlaceholderText(_translate("MainWindow", " 仅支持中文(非必填项)"))
        self.year_input.setPlaceholderText(_translate("MainWindow", " 非必填项"))
        self.regist_button.setText(_translate("MainWindow", "注  册"))
        self.search_button.setText(_translate("MainWindow", "搜 索"))
        self.year_label.setText(_translate("MainWindow", "课程年份"))
        self.keyword_label.setText(_translate("MainWindow", "关键词"))
        self.detail_button.setText(_translate("MainWindow", "查看详情"))
        self.learn_button.setText(_translate("MainWindow", "全部学习"))
        self.learn_button_2.setText(_translate("MainWindow", "学  习"))
        self.about_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; color:#ffaa00;\">WebCourse</span><span style=\" font-size:14pt; color:#ffaa00;\">，</span><span style=\" font-size:14pt;\">一款学习辅助软件。</span></p><p><span style=\" font-size:14pt;\">作者：菜菜子（xeroxYor）</span></p><p><span style=\" font-size:14pt;\">项目地址：</span><a href=\"github.com/MrBeike/webCourse.git\"><span style=\" font-size:14pt; text-decoration: underline; color:#0000ff;\">github.com/MrBeike/webCourse.git</span></a></p><p><span style=\" font-size:14pt;\">联系方式：lbbas@126.com</span></p></body></html>"))
        self.menu_list.setSortingEnabled(False)
        __sortingEnabled = self.menu_list.isSortingEnabled()
        self.menu_list.setSortingEnabled(False)
        item = self.menu_list.item(0)
        item.setText(_translate("MainWindow", "用户登录"))
        item = self.menu_list.item(1)
        item.setText(_translate("MainWindow", "项目注册"))
        item = self.menu_list.item(2)
        item.setText(_translate("MainWindow", "我的项目"))
        item = self.menu_list.item(3)
        item.setText(_translate("MainWindow", "我的课程"))
        item = self.menu_list.item(4)
        item.setText(_translate("MainWindow", "实验室"))
        item = self.menu_list.item(5)
        item.setText(_translate("MainWindow", "关于"))
        self.menu_list.setSortingEnabled(__sortingEnabled)
import webcourse_rc
